### ISSUE TITLE
Erreur libQt5Core.so.5

### ISSUE THREAD

**Issue by naub1n** [3liz/py-qgis-server#22]
Bonjour,

J'ai une erreur au chargement de l'image `3liz/qgis-map-server` avec la version docker :
```
Running Xvfb
qgisserver 1.4.2 (build 202101111305,commit f98c8ec)
Log level set to DEBUG
2021-02-09 10:14:44,242	INFO	[1]	Starting broker process
2021-02-09 10:14:44,246	INFO	[1]	Running server on port 0.0.0.0:8080
2021-02-09 10:14:44,246	INFO	[23]	Binding frontend to ipc:///tmp/qgssrv/broker/0
2021-02-09 10:14:44,248	INFO	[23]	Binding backend to ipc:///tmp/qgssrv/broker/pool0
2021-02-09 10:14:44,249	INFO	[23]	Starting ZMQ broker loop
2021-02-09 10:14:44,250	INFO	[1]	Starting client b'OWS-SERVER-1'
2021-02-09 10:14:44,252	DEBUG	[1]	Updated watch files []
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pyqgisserver/runtime.py", line 172, in run_worker_pool
    from .qgspool import Pool
  File "/usr/local/lib/python3.7/dist-packages/pyqgisserver/qgspool.py", line 20, in <module>
    from .qgsworker import QgsRequestHandler
  File "/usr/local/lib/python3.7/dist-packages/pyqgisserver/qgsworker.py", line 23, in <module>
    from qgis.PyQt.QtCore import QBuffer, QIODevice, QByteArray
  File "/usr/lib/python3/dist-packages/qgis/__init__.py", line 70, in <module>
    from qgis.PyQt import QtCore
  File "/usr/lib/python3/dist-packages/qgis/PyQt/QtCore.py", line 24, in <module>
    from PyQt5.QtCore import *
ImportError: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

Pour corriger le problème, j'ai ajouté le paquet `binutils` dans le Dockerfile puis j'ai ajouté la ligne suivante : 
`RUN strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5`
J'ai trouvé cette solution [sur cette page](https://askubuntu.com/questions/1034313/ubuntu-18-4-libqt5core-so-5-cannot-open-shared-object-file-no-such-file-or-dir), je ne sais pas si c'est la bonne solution mais tout marche bien ensuite.

J'ai constaté le problème sur les tags 3.10, 3.16, 3.16.2-1.4.2
J'ai utilisé le fichier docker-compose disponible [ici](https://github.com/3liz/lizmap-docker-compose)

**Comment by dmarteau** [comment]
Bonjour,

Je ne reproduis pas le problème ci-dessus à partir des images  mentionnées: ni en local ni sur notre infrastructure de CI où les images sont testées avant d'être poussées. 

Essayez un de lancer le serveur de manière isolée à partir `make -C docker run BUILDIMAGE=3liz/qgis-map-server:3.16`

Quelle est la version de votre kernel Linux ?

**Comment by naub1n** [comment]
Voici le résultat de la commande uname -r
3.10.0-1062.4.1.el7.x86_64
Concernant la commande que vous avez indiquée, voici le résultat:
```
[swarm@xxxxxx py-qgis-server-master]$ make -C docker run BUILDIMAGE=3liz/qgis-map-server:3.16
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
make: Entering directory `/home/swarm/py-qgis-server-master/docker'
docker run -it --rm -p 8888:8080 \
   -v /home/swarm/py-qgis-server-master:/src  \
   -v /home/swarm/py-qgis-server-master/tests/data:/projects \
   -e QGSRV_PROJECTS_SCHEMES_TEST=/src/tests/data/ \
   -e QGSRV_PROJECTS_SCHEMES_FOO=file:foobar/ \
   -e QGSRV_PROJECTS_SCHEMES_BAR=file:foobar?data={path} \
   -e QGSRV_SERVER_HTTP_PROXY=yes \
   -e QGSRV_CACHE_ROOTDIR=/projects \
   -e QGSRV_USER=1001:1001 \
   -e QGSRV_LOGGING_LEVEL=DEBUG \
   3liz/qgis-map-server:3.16
Running Xvfb
nohup: appending output to 'nohup.out'
Traceback (most recent call last):
  File "/usr/local/bin/qgisserver", line 5, in <module>
    from pyqgisserver.server import main
  File "/usr/local/lib/python3.7/dist-packages/pyqgisserver/server.py", line 21, in <module>
    from .runtime import run_server
  File "/usr/local/lib/python3.7/dist-packages/pyqgisserver/runtime.py", line 29, in <module>
    from .qgspool import create_poolserver
  File "/usr/local/lib/python3.7/dist-packages/pyqgisserver/qgspool.py", line 34, in <module>
    from .qgsworker import QgsRequestHandler
  File "/usr/local/lib/python3.7/dist-packages/pyqgisserver/qgsworker.py", line 23, in <module>
    from qgis.PyQt.QtCore import QBuffer, QIODevice, QByteArray
  File "/usr/lib/python3/dist-packages/qgis/__init__.py", line 70, in <module>
    from qgis.PyQt import QtCore
  File "/usr/lib/python3/dist-packages/qgis/PyQt/QtCore.py", line 24, in <module>
    from PyQt5.QtCore import *
ImportError: libQt5Core.so.5: cannot open shared object file: No such file or directory
make: *** [run] Error 1
make: Leaving directory `/home/swarm/py-qgis-server-master/docker'

```

**Comment by dmarteau** [comment]
Votre kernel est manifestement trop ancien (comme indiqué sur le lien ci-dessus). Il n'a aucune garanti pour que la version minimum de Qt5 pour fair tourner Qgis soit stable sur cette version du noyau. 

Les images Docker sont construites sur une image `debian:buster-slim` qui tourne normalement sur un kernel 4.19+.

**Comment by naub1n** [comment]
En effet, les mêmes manipulations semblent fonctionner sur mon PC personnel avec un Kernel 5.4.
Nous avons CentOS 7 sur nos serveurs.
Le problème ne vient donc pas de l'image, merci pour votre aide!

Il pourrait être utile d'ajouter dans la document de (docker-qgis-platform)[https://github.com/3liz/docker-qgis-platform] et/ou dans la documentation de (py-qgis-server)[https://github.com/3liz/py-qgis-server/tree/master/docker] pour docker, la version minimal requise pour le kernel de l'hôte, ou bien d'indiquer la version de l'OS sur lequel sont basées ces images.

**Comment by dmarteau** [comment]
Pushed notes about kernel version.
